/* Short, source-grounded reading notes. Titles and order come from the collection. */
const topics={
 torus:['Torus','A surface with two independent closed directions.','https://en.wikipedia.org/wiki/Torus'],
 winding:['Torus knots','Integer winding numbers determine how a path closes.','https://en.wikipedia.org/wiki/Torus_knot'],
 villarceau:['Villarceau circles','Oblique cuts reveal two families of exact circles on a torus.','https://en.wikipedia.org/wiki/Villarceau_circles'],
 braid:['Braids and interlacing','Strands alternate above and below one another.','https://en.wikipedia.org/wiki/Braid_theory'],
 approximant:['Periodic approximants','Repeating rational approximations let quasicrystalline patterns close around this torus.','https://en.wikipedia.org/wiki/Quasicrystal'],
 penrose:['Penrose tiling and quasicrystalline geometry','Ordered, nonperiodic rhomb patterns; these studies use periodic pentagrid approximants.','https://en.wikipedia.org/wiki/Penrose_tiling'],
 cairo:['Cairo pentagons','A pentagonal tiling with fourfold organisation.','https://en.wikipedia.org/wiki/Cairo_pentagonal_tiling'],
 kagome:['Kagome patterns','Corner-sharing triangles surround hexagonal openings.','https://en.wikipedia.org/wiki/Trihexagonal_tiling'],
 chair:['Chair substitution','An L-shaped tile divides into four smaller chairs.','https://en.wikipedia.org/wiki/Chair_tiling'],
 carpet:['Sierpiński carpets','Repeatedly retain eight surrounding ninths; inlays keep the central squares as tiles.','https://en.wikipedia.org/wiki/Sierpi%C5%84ski_carpet'],
 cantor:['Cantor-like constructions','Repeated paired divisions create nested strips and gaps.','https://en.wikipedia.org/wiki/Cantor_set'],
 julia:['Julia sets','Repeated complex squaring separates bounded orbits from escaping ones.','https://en.wikipedia.org/wiki/Julia_set'],
 mobius:['Möbius transformations','Complex fractional-linear maps carry circles and lines to circles and lines.','https://en.wikipedia.org/wiki/M%C3%B6bius_transformation'],
 theta:['Jacobi theta functions','Balanced ratios of quasi-periodic Fourier series create doubly periodic fields with zeros and poles.','https://dlmf.nist.gov/20.2'],
 poincare:['Poincaré-disk geometry','Hyperbolic distances place infinitely many equal-size regions inside a finite disk.','https://en.wikipedia.org/wiki/Poincar%C3%A9_disk_model'],
 farey:['Farey fractions','Reduced rational numbers organise a hierarchy of scales.','https://en.wikipedia.org/wiki/Farey_sequence'],
 ford:['Ford circles','A reduced fraction p/q gets a tangent circle of radius 1/(2q²).','https://en.wikipedia.org/wiki/Ford_circle'],
 hamiltonian:['Hamiltonian flows','A stream function generates area-preserving motion on the periodic coordinate chart.','https://en.wikipedia.org/wiki/Hamiltonian_vector_field'],
 cat:['Arnold cat-map','An integer torus map stretches and folds coordinates while preserving area.','https://en.wikipedia.org/wiki/Arnold%27s_cat_map'],
 eigen:['Laplace–Beltrami eigenmodes','Natural standing-wave shapes computed for this curved torus.','https://en.wikipedia.org/wiki/Laplace%E2%80%93Beltrami_operator'],
 critical:['Saddles, centres and separatrices','Critical points organise contours; saddle passages change which level-set regions connect.','https://en.wikipedia.org/wiki/Separatrix'],
 morse:['Changing level-set connections','Crossing a saddle value joins or separates contour components.','https://en.wikipedia.org/wiki/Morse_theory'],
 vortex:['Phase vortices','The phase winds around a zero of a complex field.','https://en.wikipedia.org/wiki/Optical_vortex'],
 truchet:['Truchet tilings','Simple tile orientations join local arcs into long paths.','https://en.wikipedia.org/wiki/Truchet_tiles'],
 moore:['Moore curves','A closed recursive space-filling curve, drawn here at finite depth.','https://en.wikipedia.org/wiki/Moore_curve'],
 pythagoras:['Pythagorean dissections','Squares and triangles rearrange within a shared boundary.','https://en.wikipedia.org/wiki/Pythagorean_theorem'],
 kirigami:['Kirigami','Cuts let a sheet open into moving apertures and folds.','https://en.wikipedia.org/wiki/Kirigami'],
 origami:['Origami','Creases coordinate the movement of connected panels.','https://en.wikipedia.org/wiki/Origami'],
 guilloche:['Guilloché and engine-turned engraving','Repeated interlacing contours make finely engraved ornament.','https://en.wikipedia.org/wiki/Guilloch%C3%A9'],
 fourier:['Fourier interference','Complex waves add; their phases determine the resulting pattern.','https://en.wikipedia.org/wiki/Fourier_series'],
 talbot:['Talbot revival','Quadratic Fourier phases reconstruct shifted copies at rational fractions of a cycle.','https://cris.technion.ac.il/en/publications/integer-fractional-and-fractal-talbot-effects/'],
 spinor:['Dirac belt trick','A complete 720° turn can untwist continuously while the outer attachment stays fixed.','https://arxiv.org/abs/2107.01681'],
 phason:['Phason flips','Local vertex rearrangements change tile adjacency in a quasicrystalline approximant.','https://arxiv.org/abs/0901.4441'],
 covering:['Torus covering maps','Integer maps repeat one global organisation at successively smaller scales.','https://en.wikipedia.org/wiki/Covering_space'],
 recursion:['Recursion and scale','A construction repeats within its own smaller parts.','https://en.wikipedia.org/wiki/Recursion'],
 quadtree:['Quadtrees','Repeated four-way divisions organise nested square regions.','https://en.wikipedia.org/wiki/Quadtree'],
 golden:['Golden ratio','Unequal parts repeat the same proportion at successive scales.','https://en.wikipedia.org/wiki/Golden_ratio'],
 voronoi:['Voronoi cells','Each point belongs to its nearest moving seed.','https://en.wikipedia.org/wiki/Voronoi_diagram'],
 tessellation:['Tessellation','Tiles share boundaries and fill a surface without gaps.','https://en.wikipedia.org/wiki/Tessellation'],
 symmetry:['Rotational symmetry','Related orientations repeat around a common centre.','https://en.wikipedia.org/wiki/Rotational_symmetry']
};
const influences={
 escher:['M. C. Escher','Shared animal contours, figure–ground exchange and recursive worlds.','https://mcescher.com/'],
 bleuje:['Étienne Jacob / bleuje','Precisely phased geometric loops and choreographed motion.','https://bleuje.com/'],
 wavegrower:['Wavegrower','Monochrome oscillations and collective waves of simple forms.','https://wavegrower.tumblr.com/'],
 alex:['Alex Grey','Watching eyes, branching anatomy and visionary architecture.','https://www.alexgrey.com/'],
 allyson:['Allyson Grey','Nested grids and the interplay of order and disorder.','https://www.allysongrey.com/']
};
// [one short explanation, mathematical topics, artistic references]
const studies={
 138:['A turning-square dissection repeats inside its own moving centre.',['pythagoras','recursion'],['bleuje']],
 135:['Four child regions grow, subdivide and retract into their parents.',['quadtree'],['bleuje']],
 136:['Eight squares grow around a receding centre, then repeat the same operation.',['carpet'],['escher']],
 137:['Paired strips divide repeatedly on alternating axes.',['cantor'],['allyson']],
 139:['Nested apertures open into eyes as each generation grows.',['recursion'],['alex']],
 140:['Golden-section proportions guide a growing hierarchy of unequal regions.',['golden'],['allyson']],
 141:['Recursive partitions grow inside a periodic pentagrid mosaic.',['penrose','approximant','golden'],['allyson']],
 142:['Nested quadrilaterals turn and contract inside each pentagrid rhomb.',['penrose','approximant'],['bleuje']],
 125:['Moving seed rows change square cells into hexagons and back.',['voronoi'],['bleuje']],
 126:['Four seed families move between pentagonal and square partitions.',['cairo','voronoi'],['bleuje']],
 127:['Square corners retreat, growing diamonds between the resulting octagons.',['tessellation'],['bleuje']],
 128:['A turning square and four corner triangles always fill their parent.',['pythagoras'],['bleuje']],
 129:['Four paths meet at a saddle and reconnect with different neighbours.',['truchet','morse'],['wavegrower']],
 130:['Shared square boundaries unfold into an interlocking flock of swans.',['tessellation'],['escher']],
 131:['Fish and swans exchange form through continuously shared contours.',['tessellation'],['escher']],
 132:['Three reptile orientations emerge from a hexagonal mosaic.',['tessellation','symmetry'],['escher']],
 133:['Diamond cells develop wings, antennae and shared moth outlines.',['tessellation'],['escher']],
 134:['Scales become wing veins as interlocking fish turn into moths.',['tessellation'],['escher']],
 101:['Shared square borders flex around turning frames and optional nested inlays.',['tessellation','symmetry'],['bleuje']],
 102:['Three coordinated tones move through a hexagonal tessellation.',['tessellation'],['wavegrower']],
 103:['Two triangle orientations exchange tone along closed windings.',['tessellation','winding'],['wavegrower']],
 104:['Three rhombi suggest ambiguous cubes as their facet tones change.',['tessellation'],['escher']],
 105:['Octagons and small square interstices share a continuous inlay.',['tessellation'],['escher']],
 106:['Moving seed orbits produce a breathing Cairo-type pentagonal mosaic.',['cairo','voronoi'],['bleuje']],
 107:['Horizontal and vertical dominoes interlock in a herringbone current.',['tessellation'],['wavegrower']],
 108:['Hexagons and triangles exchange tone through their shared neighbourhoods.',['kagome'],['wavegrower']],
 109:['Shared cuts curl square tiles into complementary waves.',['tessellation'],['escher']],
 121:['Thick and thin rhombi exchange light in a closed pentagrid approximant.',['penrose','approximant'],['allyson']],
 122:['Arcs join across rhomb-edge midpoints into long mosaic pathways.',['penrose','approximant','truchet'],['escher']],
 123:['Partitions breathe between complementary golden-section proportions inside rhombi.',['golden','approximant'],['allyson']],
 124:['Four-way divisions give rhombi a visible ancestry of smaller tiles.',['quadtree','penrose','approximant'],['allyson']],
 92:['Rhomb halves fold about shared diagonals with contrasting tones.',['approximant','origami'],['bleuje']],
 93:['Nested golden contours open within raised rhombic chambers.',['golden','approximant'],['allyson']],
 94:['Paired bands weave across a pentagrid mosaic.',['braid','approximant'],['wavegrower']],
 68:['Nested golden frames rise from a periodic pentagrid.',['penrose','approximant'],['allyson']],
 69:['Rhomb families exchange tone while arcs share a travelling phase.',['penrose','approximant'],['wavegrower']],
 70:['A coherent wave raises and lowers hinged quasicrystalline rhombi.',['penrose','approximant','origami'],['bleuje']],
 114:['One quadrant remains intact while its neighbours subdivide.',['quadtree'],['allyson']],
 115:['Each L-shaped chair contains four smaller chairs.',['chair','approximant'],['escher']],
 116:['Central triangles remain as tiles while their three neighbours subdivide.',['tessellation'],['escher']],
 117:['Central ninths remain as tiles inside a recursively filled carpet.',['carpet'],['allyson']],
 118:['Alternating rectangular divisions breathe without opening gaps.',['cantor','tessellation'],['bleuje']],
 119:['Quarter-turns reveal the directional ancestry of nested square regions.',['quadtree','symmetry'],['bleuje']],
 120:['Quarter-circle paths connect across recursively divided squares.',['truchet','quadtree'],['escher']],
 67:['Corner cubes repeat and counterturn at progressively smaller scales.',['recursion','symmetry'],['bleuje']],
 21:['Fixed shades stay on cube faces as delayed rotations cross the chamber.',['symmetry'],['bleuje']],
 56:['Nested frames turn about differently phased axes.',['symmetry'],['bleuje']],
 59:['A perforated Sierpiński carpet opens into delayed hinged shutters.',['carpet','kirigami'],['bleuje']],
 25:['Cuts and coordinated hinges open a sheet into moving vaults.',['kirigami','origami'],['bleuje']],
 27:['Nested pleated tiers unfold in alternating directions.',['kirigami','origami'],['bleuje']],
 22:['Six curved blades curl around a changing aperture.',['symmetry'],['bleuje']],
 13:['Broad ribbon families exchange over–under roles at their crossings.',['braid','winding'],['wavegrower']],
 60:['Two oblique circle families carry ribbons with contrasting tones.',['villarceau','braid'],['bleuje']],
 61:['Each cable bundle contains three groups of three smaller, materially shaded strands.',['braid','winding'],['bleuje']],
 28:['Nine-ribbon bundles interlace along closed torus windings.',['braid','winding'],['wavegrower']],
 23:['Three-strand cables close along trefoil paths with real depth at crossings.',['braid','winding'],['bleuje']],
 17:['Coprime winding numbers organise intersecting woven bundles.',['braid','winding'],['wavegrower']],
 0:['Strands pass successively above and below their neighbours.',['braid'],['wavegrower']],
 33:['Paired ribbons change places in an alternating interlacing rhythm.',['braid'],['bleuje']],
 41:['Two families of exact torus circles carry travelling intersections.',['villarceau'],['bleuje']],
 95:['A changing quadratic Julia family reveals nested escape contours.',['julia','winding'],['escher']],
 98:['Binary cell parity determines the handedness of nested, paperfold-inspired frames.',['origami','covering'],['bleuje']],
 78:['Smaller eyes occupy the spaces inside larger eyelids.',['covering'],['alex']],
 79:['Six eye-bearing sectors rotate around a breathing wheel and periodic lattice.',['symmetry'],['alex']],
 80:['Ribbed columns, eye contours and sinusoidal branches form repeating architecture.',['symmetry'],['alex']],
 75:['An integer torus automorphism repeats and stretches nested square worlds.',['cat','covering'],['allyson']],
 76:['A ternary carpet carries different light phases at each recursive scale.',['carpet','covering'],['allyson']],
 83:['Logarithmic scale cycling passes ornament between successive generations.',['recursion'],['escher']],
 85:['Recursive Truchet paths reconnect across smaller inherited chambers.',['truchet','covering'],['escher']],
 53:['Finite torus coverings repeat linked eyes at nested scales.',['covering','theta'],['alex','allyson']],
 50:['Eye-bearing circles turn within a counter-rotating corona.',['symmetry'],['alex']],
 49:['Rational positions organise a hierarchy of tangent, eye-bearing circles.',['farey','ford'],['alex']],
 47:['Eye rosettes shrink towards the boundary of a hyperbolic disk.',['poincare','mobius'],['escher','alex']],
 51:['Branching ribs and nested eyes join into a continuous architectural field.',['recursion'],['alex']],
 97:['Real and imaginary wave components exchange connected dark and light regions.',['fourier','morse'],['wavegrower']],
 73:['A changing nodal field joins and separates neighbouring tesserae.',['morse','fourier'],['escher']],
 74:['Broad ribbon families exchange figure and ground through a shared field.',['braid'],['escher','wavegrower']],
 30:['Opposing rotations open and close a linked square lattice.',['symmetry','tessellation'],['bleuje']],
 32:['Six petals turn together around a shared hexagonal aperture.',['symmetry'],['bleuje']],
 35:['Four linked orbits turn with counter-rotating internal markers.',['symmetry','fourier'],['bleuje']],
 38:['A saddle changes the pairing of four fixed boundary connections.',['critical','morse'],['wavegrower']],
 34:['Contour islands join and separate as their saddle levels change.',['critical','morse'],['wavegrower']],
 26:['Moving seed quartets change the neighbours of their surrounding cells.',['voronoi'],['bleuje']],
 8:['Connected arcs move through a smoothly sheared tiling.',['truchet'],['wavegrower']],
 99:['Integer torus maps repeat changing saddle connections at nested scales.',['critical','morse','covering'],['allyson']],
 81:['Curved-torus eigenmodes interweave into a moving nodal fabric.',['eigen','fourier'],['wavegrower']],
 82:['Complex-field zeros migrate through lace-like phase contours.',['vortex','fourier'],['wavegrower']],
 84:['Area-preserving shears stretch filaments and then undo the deformation.',['hamiltonian'],['wavegrower']],
 19:['Computed Laplace–Beltrami modes combine into standing and travelling contours.',['eigen','fourier'],['wavegrower']],
 15:['Hamiltonian currents stretch fine strands without compressing coordinate area.',['hamiltonian'],['wavegrower']],
 16:['Engraved streamlines gather around centres, saddles and their separating curves.',['hamiltonian','critical'],['wavegrower']],
 18:['Interfering complex waves create zeros surrounded by winding phase rays.',['vortex','fourier'],['wavegrower']],
 20:['Distance contours follow a finite-depth, closed Moore curve.',['moore','hamiltonian'],['wavegrower']],
 4:['Interfering contours form rosettes and engine-turned ornament.',['guilloche','fourier'],['wavegrower']],
 10:['A harmonic lace repeatedly separates and reconnects.',['fourier','morse'],['wavegrower']],
 12:['Wave contours widen into dark ribbons and narrow into engravings.',['fourier','guilloche'],['wavegrower']],
 14:['Meridian strands compress and spread through a closed winding flow.',['winding','hamiltonian'],['wavegrower']],
 7:['Two coherent waves move and swell a constellation of beads.',['fourier'],['wavegrower']],
 11:['Veined lenses lean and rise in alternately phased rows.',['symmetry'],['wavegrower']],
 145:['Rosettes disperse into fractional wave revivals, then reconstruct exactly.',['talbot','fourier'],['wavegrower']],
 146:['Theta-function zeros and poles exchange, reversing nested eyes and their surrounding light.',['theta','covering'],['alex','allyson']],
 147:['Turning cubes carry ribbons through a closed 720° belt-trick cycle.',['spinor','braid'],['bleuje']],
 148:['Travelling fronts flip rhomb neighbours; inset contours follow the tiles through continuously filled transitions.',['phason','penrose','approximant'],['allyson']]
};
module.exports={topics,influences,studies};
